only_rules:
  - closure_spacing
  - colon
  - empty_enum_arguments
  - fatal_error_message
  - force_try
  - implicitly_unwrapped_optional
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - operator_usage_whitespace
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - trailing_newline
  - type_name
  - unused_closure_parameter
  - unused_optional_binding
  - vertical_whitespace
  - void_return
  - custom_rules
  - control_statement
  - force_unwrapping

excluded:
  - Carthage
  - Pods

colon:
  apply_to_dictionaries: false

indentation: 1

custom_rules:

  overlapping_views:
    severity: warning
    regex: "\\.overlay\\((.*)\\)"
    message: "Overlay is deprecated"
    correctOverlappingViews: true
